# MyCra Death Message v2.3.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

# Output to server.log and console.
loggingDeathMessage: true

# Suppress death message exclude OPs.
suppressDeathMessage: false

# Append world name to prefix.
prefixWorld: false

