# ${project.name} v${project.version}
# @author     tsuttsu305, ucchy
# @license    GPLv3
# @copyright  Copyright tsuttsu305, ucchy 2013

# Output to server.log and console.
loggingDeathMessage: true

# Suppress death message exclude OPs.
suppressDeathMessage: false

# Append world name to prefix.
prefixWorld: false

